# -*- coding: utf-8 -*-
"""Ustrinha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyrbThRSZu2YywPHIQFCHMYdXfFJEmWU
"""

print("Olá, meu nome é Ustra.")

#Exemplo 2 - Programa para calcular a média de altura

print("esse programa irá calcular a média de altura de 5 pessoas")

altura1 = float(input("Digite a altura da primeira pessoa"))
altura2 = float(input("Digite a altura da primeira pessoa"))
altura3 = float(input("Digite a altura da primeira pessoa"))
altura4 = float(input("Digite a altura da primeira pessoa"))
altura5 = float(input("Digite a altura da primeira pessoa"))


média = (altura1 + altura2 + altura3 + altura4 + altura5) / 5

print("A média das alturas é:", média)

#Exemplo 3 - Programa para importa biblioteca math

import math

print("A raiz quadrada de 9 é:", math.sqrt(9))
print("A área da circuferência de raio 2 é", math.pi * math.pow(2, 2))
print("A área da circuferência de raio 2 é", math.pi * (2)**2)

#Trabalhando com a função print

print("Hello, Ustrinha")

print("Raissa")

print("Anakin")
print("Radiohead")

print("Down came the rain\nand washed the spider out.")

#2.1.9

print("The itsy bitsy spider" , "climbed up" , "the waterspout.")

print("My name is", "Python" , end=" ")
print("Monty Python.")

print("My", "name", "is", "Monty", "Python." , sep="+")
print("Programming", "essentials", "in...Python", sep="***")
print("My\nname\nis\nBond.", end=" ")
print("\nMeu\nnome\né\nRaissa\n" , end=" ")

print("&", "fish", "chips", sep=", ")

print('Greg\'s book.')
print("'Greg's book.'")
print('"Greg\'s book."')
print("Greg\'s book.")

print("Greg's book.")

print("I like \"Monty Python\"")

print(True > False)

print("\"I'm\"\n\"\"learning\"\"\n\"\"\"Python\"\"\"")